services:
  rust_primes:
    build: 
      context: ./rust_primes
      dockerfile: Dockerfile
      command: echo "warp running on http://0.0.0.0:3030"
    ports:
      - "3030:3030"
  py_primes:
    build:
      context: ./fastapi_primes
      dockerfile: Dockerfile
    ports:
      - "80:80"

